server:
  port: 8080
  error:
    include-message: never
    include-binding-errors: always
    include-stacktrace: on-param
    include-exception: false

spring:
  application:
    name: news-sender-api
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: augustomailsenderapi@gmail.com
    password: uluc gfjk jkwo pysa
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      protocol: smtp
      test-connection: false
  task:
    scheduling:
      cron: 0 0 8 * * ?

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/news-sender-db
    username: admin
    password: 123456
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show_sql: true
